config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'
  resources :cours, only: [:index]
  get "/aarrr256" => "pages#aarrr256"
  get "/statistiques975" => "pages#statistiques975"
  get "/prototyping194V3" => "pages#prototyping194V3"
  get "/prototyping278g9" => "pages#prototyping278g9"
  get "/googleanalytics9565" => "pages#googleanalytics9565"
  get "/facebook666S" => "pages#facebook666S"
  get "/adwords876T" => "pages#adwords876T"
  get "/form" => "pages#form"

  get "/pmf46292" => "pages#pmf46292"
  get "/growth8933G3" => "pages#growth8933G3"

  get "/retargetingZW678" => "pages#retargetingZW678"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/cours_controller.rb
class CoursController < ApplicationController
  def index
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
skip_before_action :authenticate_user!

  def home
  end


  def prototyping194V3
  end


  def prototyping278g9
  end


  def statistiques975
  end

  def aarrr256
  end

  def googleanalytics9565
  end

  def pmf46292
  end

  def adwords876T
  end

  def retargetingZW678
  end

  def facebook666S
  end


  def growth8933G3
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cours_helper.rb
module CoursHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cours/index.html.erb
<div id="large-header" class="large-header " style="background-image:url('<%= image_path "image_header2.jpg" %>')">
  <canvas id="demo-canvas"></canvas>
  <div id="home" class="baseline d-flex align-items-center justify-content-center">
    <div class="baseline-text">
      <h1>Welcome !<h1>
      <a class="btn btn-purple-header hvr-float pulse" href="#aarrr"">Accéder aux cours</a>
    </div>
  </div>
</div>




<div id="aarrr" class="banner-wrapper banner-color-purple" style="background-image: linear-gradient(180deg, rgba(0,0,0,1) 10%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours2.jpg" %>');">
  <div class="banner" >
    <h1>AARRR</h1>
    <div class="banner-underline"></div>
    <div class="container banner-wrapper-items">
      <div class="row">
        <div class="col-8 mx-auto">
          <div class="row">
            <div class="col-6">
              <div class="banner-banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours_aarrr.jpg" %>');">
                <div class="banner-banner-content d-flex justify-content-center">
                  <div class="p-2">
                    <h2>Le framework - AARRR</h2>
                    <h3>Cours - 1</h3>
                    <%= link_to  "Voir le cours", aarrr256_path,  class: "btn btn-cours btn-purple hvr-float" %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-6">
              <div class="banner-banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours_statistic.jpg" %>');">
                <div class="banner-banner-content d-flex justify-content-center">
                  <div class="p-2">
                    <h2>Statistiques</h2>
                    <h3>Cours - 3</h3>
                    <%= link_to  "Voir le cours", statistiques975_path,  class: "btn btn-cours btn-purple hvr-float" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div id="activation" class="banner-wrapper banner-color-green" style="background-image: linear-gradient(180deg, rgba(0,0,0,1) 10%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours4.jpg" %>');">
  <div class="banner" >
    <h1>Activation</h1>
    <div class="banner-underline"></div>
    <div class="container banner-wrapper-items">
      <div class="row">
        <div class="col-8 mx-auto">
          <div class="row">
            <div class="col-6">
              <div class="banner-banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours_prototyping1.jpg" %>');">
                <div class="banner-banner-content d-flex justify-content-center">
                  <div class="p-2">
                    <h2>Prototyping I</h2>
                    <h3>Cours - 2</h3>
                    <%= link_to  "Voir le cours", prototyping194V3_path,  class: "btn btn-cours btn-green hvr-float" %>
                  </div>s
                </div>
              </div>
            </div>
            <div class="col-6">
              <div class="banner-banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours_prototyping2.jpg" %>');">
                <div class="banner-banner-content d-flex justify-content-center">
                  <div class="p-2">
                    <h2>Prototyping II</h2>
                    <h3>Cours - 4</h3>
                    <%= link_to  "Voir le cours", prototyping278g9_path,  class: "btn btn-cours btn-green hvr-float" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="acquisition" class="banner-wrapper banner-color-red" style="background-image: linear-gradient(180deg, rgba(0,0,0,1) 10%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours5.png" %>');">
  <div class="banner" >
    <h1>Acquisition</h1>
    <div class="banner-underline"></div>
    <div class="container banner-wrapper-items">
      <div class="row">
        <div class="col-12">
          <div class="row">
            <div class="col-4">
              <div class="banner-banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours_ga.jpg" %>');">
                <div class="banner-banner-content d-flex justify-content-center">
                  <div class="p-2">
                    <h2>Google Analytics</h2>
                    <h3>Cours - 6</h3>
                    <%= link_to  "Voir le cours", googleanalytics9565_path ,  class: "btn btn-cours btn-red hvr-float" %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-4">
              <div class="banner-banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours_fb.jpg" %>');">
                <div class="banner-banner-content d-flex justify-content-center">
                  <div class="p-2">
                    <h2>Facebook Ads</h2>
                    <h3>Cours - 7</h3>
                     <%= link_to  "Voir le cours", facebook666S_path ,  class: "btn btn-cours btn-red hvr-float" %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-4">
              <div class="banner-banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours_adwords.jpg" %>');">
                <div class="banner-banner-content d-flex justify-content-center">
                  <div class="p-2">
                    <h2>Adwords & SEO</h2>
                    <h3>Cours - 8</h3>
                    <%= link_to  "Voir le cours", adwords876T_path ,  class: "btn btn-cours btn-red hvr-float" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="retention" class="banner-wrapper banner-color-blue" style="background-image: linear-gradient(180deg, rgba(0,0,0,1) 10%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours6.jpg" %>');">
  <div class="banner" >
    <h1>Retention & Referal</h1>
    <div class="banner-underline"></div>
    <div class="container banner-wrapper-items">
      <div class="row">
        <div class="col-4 mx-auto">
          <div class="row">
            <div class="col-12">
              <div class="banner-banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours_retargeting.jpg" %>');">
                <div class="banner-banner-content d-flex justify-content-center">
                  <div class="p-2">
                    <h2>Retargeting</h2>
                    <h3>Cours - 9</h3>
                    <%= link_to  "Voir le cours", retargetingZW678_path ,  class: "btn btn-cours btn-blue hvr-float" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div id="philosophie" class="banner-wrapper" style="background-image: linear-gradient(180deg, rgba(0,0,0,1) 10%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours3.jpg" %>');">
  <div class="banner" >
    <h1>Philosophie</h1>
    <div class="banner-underline"></div>
    <div class="container banner-wrapper-items">
      <div class="row">
        <div class="col-8 mx-auto">
          <div class="row">
            <div class="col-6">
              <div class="banner-banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours_growth.jpg" %>');">
                <div class="banner-banner-content d-flex justify-content-center">
                  <div class="p-2">
                    <h2>Start-up = Growth</h2>
                    <h3>Cours - 10</h3>
                    <%= link_to  "Voir le cours", growth8933G3_path ,  class: "btn btn-cours btn-yellow hvr-float" %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-6">
              <div class="banner-banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours_pmf.jpg" %>');">
                <div class="banner-banner-content d-flex justify-content-center">
                  <div class="p-2">
                    <h2>Product Market Fit</h2>
                    <h3>Cours - 5</h3>
                    <%= link_to  "Voir le cours", pmf46292_path ,  class: "btn btn-cours btn-yellow hvr-float" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdn.optimizely.com/js/10193084842.js"></script>
    <title>Guide to Galaxy</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-113294460-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-113294460-1');
    </script>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="large-header" class="large-header " style="background-image:url('<%= image_path "image_header.jpg" %>')">
  <canvas id="demo-canvas"></canvas>
  <div id="home" class="baseline d-flex align-items-center justify-content-center">
    <div class="baseline-text">
      <h1 id="home-title-h1">Guide to Galaxy</h1>
      <h2>Construction d'un E-business autour du framework AARRR</h2>
      <%= link_to "Voir les cours" , cours_path, class: "btn btn-purple-header hvr-float", id: "home-button" %>
    </div>
  </div>
</div>

app/views/pages/statistiques.html.erb
<div class="cours-header d-flex align-items-center justify-content-center" style="background-image: linear-gradient(180deg, rgba(0,0,0,1) 10%, rgba(0,0,0,0.5) 50%), url('<%= image_path "image_cours2.jpg" %>');">
  <h1>Statistiques</h1>
</div>



<div class="container cours-page">
  <div class="row">
    <div class="col-sm-10 mx-auto">
      <div class="title-underline-purple">
        <h2>Cours</h2>
      </div>

      <div class="paragraphe-cours">
        <h3>1 - Définir vos KPI </h3>
        <div class="text-corps">
          <p>Comme on a pu le voir dans la présentation du diagramme AARRR il faut <span class="highlight-yellow">se fixer un KPI par step</span> puis on essaie de l’améliorer, à chaque fois on prend le KPI le plus en aval possible </p>
        </div>
      </div>

      <div class="paragraphe-cours">
        <h3>2 - Formuler une hypothèse  </h3>
        <div class="text-corps">
          <ul>
            <li>
              <p>Ma campagne de marketing est elle pertinente ?</p>
            </li>
            <li>
              <p>Les changements fait sur mon App sont-ils bons ? </p>
            </li>
            <li>
              <p>Dois-je changer de princing ?</p>
            </li>
            <li>
              <p>Dois-je faire payer les frais d’expédition ?</p>
            </li>
            <li>
              <p>La modification du design de mon site a t'il un impact sur les ventes ?</p>
            </li>
            <li>
              <p>Quel libellé du bouton de paiement est il le meilleur ?</p>
            </li>
          </ul>
        </div>
      </div>

      <div class="paragraphe-cours">
        <h3>3 - Definir le test  </h3>
        <div class="text-corps">
          <p>Quelle est votre audience cible ?
            <br> Que voulez-vous qu’ils fassent ?
            <br> Pourquoi devraient ils le faire ?
            <br> <br> Chercher à savoir <span class="highlight-yellow">QUI fera QUOI et POURQUOI</span>, suffisamment pour améliorer le KPI ciblé.
            <br> <br> <span class="bold">Par exemple :</span> Les cyclistes vont faire un devis pour recevoir des informations complémentaires
            sur le produit d'assurance </p>
        </div>
      </div>

      <div class="paragraphe-cours">
        <h3>4 - Mesurer </h3>
        <div class="text-corps">
          <p>Mesurer les résultats du test pour définir si c’est un succès ou pas. Ensuite itérer pour continuer à améliorer. </p>
        </div>
      </div>


      <div class="paragraphe-cours">
        <h3>5 - Comment savoir si un test est un succès ou non ?</h3>
        <div class="text-corps">
          <p> Utiliser ce petit module de calcul : <a href="www.evanmiller.org/ab-testing/chi-squared.html" target="_blank">www.evanmiller.org/ab-testing/chi-squared.html</a></p>
        </div>
      </div>



      <div class="title-underline-purple">
        <h2>Exemples</h2>
      </div>

      <div class="paragraphe-cours">
        <h3>Exemple 1</h3>
        <div class="text-corps">
          <p> faisons un A/B test sur 200 personnes, 100 personnes vont voir la version A et les 100 autres la versions B. La version A convertie à 14%, la version B à 20%
          <img src="<%= image_path "stat-1.jpg" %>" alt="" style="width:100%; height:100%;">
          <br><br><span class="highlight-yellow">D’un point de vue statistique il est impossible de distinguer les deux versions pour savoir quelle est la meilleure</span>.
          <br><br>Dans ce cas précis on a 95% (de confiance statistique) de chance que la réalité soit dans les fourchettes suivantes :
          <br><br> 8,5% - 22,1% et 13,3% - 28,9%</p>
        </div>
      </div>

      <div class="paragraphe-cours">
        <h3>Exemple 2</h3>
        <div class="text-corps">
          <p>
            On refait la même expérience avec 1000 personnes par test
            <img src="<%= image_path "stat-2.jpg" %>" alt="" style="width:100%; height:100%;">
            <br><br><span class="highlight-yellow">Dans ce cas là la version 2 est meilleure car on a un échantillon assez grand</span>.
            <br><br>Dans ce cas précis on a 95% (de confiance statistique) de chance que la réalité soit dans les fourchettes suivantes :
            <br><br>12% - 16,3% et 17,6% - 22,6%
          </p>
        </div>
      </div>

      <div class="paragraphe-cours">
        <h3>Exemple 3</h3>
        <div class="text-corps">
        <p>
          Faisons un A/B test sur 1100 personnes, 1000 personnes vont voir la version A et les 100 autres la versions B.
          <br><br>La version A convertie à 14%, la version B à 20%
          <img src="<%= image_path "stat-3.jpg" %>" alt="" style="width:100%; height:100%;">
          <br><br><span class="highlight-yellow">D’un point de vue statistique il est impossible de distinguer les deux versions pour savoir quelle est la meilleure</span>.
          <br><br>Dans ce cas précis on a 95% (de confiance statistique) de chance que la réalité soit dans les fourchettes suivantes :
          <br><br>12% - 16.3% et 13.3% - 28.9%
        </p>
        </div>
      </div>

      <div class="paragraphe-cours">
        <h3>Exemple 4</h3>
        <div class="text-corps">
        <p>
          Faisons un A/B test sur 1100 personnes, 1000 personnes vont voir la version A et les 100 autres la versions B.
          <br><br><span class="highlight-yellow">La version A convertie à 14%, la version B à 30%</span>
          <img src="<%= image_path "stat-4.jpg" %>" alt="" style="width:100%; height:100%;">
          <br><br>Dans ce cas précis on a 95% (de confiance statistique) de chance que la réalité soit dans les fourchettes suivantes :
          <br><br>12% - 16.3% et 21,9% - 39,6%
        </p>
        </div>
      </div>


      <div class="paragraphe-cours">
        <h3>Conclusion</h3>
        <div class="text-corps">
        <p><span class="highlight-yellow">Plus vos échantillons sont petits plus les résultats devront être très éloignés pour pouvoir
        dire si l'on a un résultat significatif</span>.
        Le travail est donc de faire des changements radicaux afin de faire varier significativement nos résultats.</p>
        </div>
      </div>

      <div class="paragraphe-cours">
        <h3>Exemple 5</h3>
        <div class="text-corps">
        <p>On va regarder à 10% près maintenant si le résultat du test est meilleur ou non. Quel est donc la taille des échantillons à avoir.
        <br><br>Supposons que nous voulons 5% de conversion on doit donc être sur l’intervalle 4.5% - 5.5%
        <img src="<%= image_path "stat-5.jpg" %>" alt="" style="width:100%; height:100%;">
        <br><br> <span class="highlight-yellow">Les mathématiques disent ici qu’il faut 30 244 personnes.</span></p>
        <br>
        <p>Outil en ligne pour calculer cela : <a href="http://www.evanmiller.org/ab-testing/sample-size.html">http://www.evanmiller.org/ab-testing/sample-size.html</a></p>
        </div>
      </div>

      <div class="paragraphe-cours">
        <h3>Exemple 6</h3>
        <div class="text-corps">
        <p><span class="bold">Cas réel (Quelle est la meilleure version ?) :</span></p>
        <img src="<%= image_path "stat-6.jpg" %>" alt="" style="width:100%; height:auto;">
        <p><span class="bold">Résultat :</span></p>
        <img src="<%= image_path "stat-7.jpg" %>" alt="" style="width:100%; height:auto;">
        </div>
      </div>

      <div class="paragraphe-cours">
        <h3>Conclusion</h3>
        <div class="text-corps">
        <p><span class="highlight-yellow">Si on veut mesurer de petites variations il faut beaucoup de monde</span></p>
        </div>
      </div>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="alert alert-info alert-dismissible alert-custom fade show" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert alert-warning alert-dismissible alert-custom fade show" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= alert %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-shrink navbar-expand-lg navbar-dark fixed-bottom" id="mainNav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand js-scroll-trigger" href="/"></a>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav mx-auto">

      <% if user_signed_in? %>

      <li class="nav-item">
        <a class="nav-link" href="https://guidetogalaxy.herokuapp.com/cours#home" id="btn-antivol-nav">home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://guidetogalaxy.herokuapp.com/cours#aarrr" id="btn-faq-nav">AARRR</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://guidetogalaxy.herokuapp.com/cours#activation" id="btn-challenge-nav">Activation</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://guidetogalaxy.herokuapp.com/cours#acquisition" id="btn-challenge-nav">Acquisition</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://guidetogalaxy.herokuapp.com/cours#retention" id="btn-challenge-nav">Rétention & Referal</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://guidetogalaxy.herokuapp.com/cours#philosophie" id="btn-antivol-nav">philosophie</a>
      </li>
      <li class="nav-item">
        <%= link_to "Deconnexion", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>


      <% else %>

      <li class="nav-item">
        <%= link_to "Connexion", new_user_session_path, class: "nav-link nav-link-blue", id:"connexion-button" %>
      </li>
      <li class="nav-item">
        <%= link_to "Inscription", new_user_registration_path, class: "nav-link", id:"inscription-button" %>
      </li>

      <% end %>

    </ul>
  </div>
</nav>